Unify secrets/variables preconditions checks

diff --git a/.github/workflows/build_linux.yml b/.github/workflows/build_linux.yml
--- a/.github/workflows/build_linux.yml
+++ b/.github/workflows/build_linux.yml
@@ -55,7 +55,7 @@ jobs:
     - name: Exit if current release branch configuration is incorrect
       if: ${{ github.event_name == 'schedule' && github.event.schedule == '0 5 */1 */1 *' && env.CURRENT_RELEASE_BRANCH == '' }}
       run: |
-        echo "::error::CURRENT_RELEASE_BRANCH is not set"
+        echo "::error::CURRENT_RELEASE_BRANCH is empty"
         exit 1
     - name: Clone repository (default)
       uses: actions/checkout@v4
@@ -91,7 +91,7 @@ jobs:
         if [[ "$BUILD_MODE" == "testing" || "$BUILD_MODE" == "stable" ]]; then
           DO_UPDATE_TS='true'
           if [ -z "${{ secrets.TRANSIFEX_API_TOKEN }}" ]; then
-            echo "warning: not set TRANSIFEX_API_TOKEN, update .ts disabled"
+            echo "::warning::TRANSIFEX_API_TOKEN is empty; updating .ts files disabled"
             DO_UPDATE_TS='false'
           fi
         fi
@@ -124,6 +124,15 @@ jobs:
           SENTRY_URL=https://sentry.musescore.org/api/3/minidump/?sentry_key=$SENTRY_SERVER_SANDBOX_KEY
         fi
 
+        DO_PUBLISH='false'
+        if [[ "${{ inputs.publish }}" == "on" || ("${{ github.event_name }}" == "schedule" && $BUILD_MODE == 'nightly') ]]; then
+          DO_PUBLISH='true'
+          if [ -z "${{ secrets.OSUOSL_SSH_ENCRYPT_SECRET }}" ]; then
+            echo "::warning::OSUOSL_SSH_ENCRYPT_SECRET is empty; not publishing to OSUOSL"
+            DO_PUBLISH='false'
+          fi
+        fi
+
         ADD_INFO="_${GITHUB_REF#refs/heads/}"
         if [ "${{ github.event_name }}" == "schedule" ] && [ "${{ github.event.schedule }}" == "0 5 */1 */1 *" ]; then ADD_INFO="_${{ env.CURRENT_RELEASE_BRANCH }}"; fi
         if [ "${{ github.event_name }}" == "pull_request" ]; then ADD_INFO="_${{ github.event.pull_request.number }}_${pull_request_title}"; fi
@@ -137,6 +146,7 @@ jobs:
         echo "DO_UPLOAD_SYMBOLS=$DO_UPLOAD_SYMBOLS" | tee -a $GITHUB_ENV
         echo "SENTRY_PROJECT=$SENTRY_PROJECT" | tee -a $GITHUB_ENV
         echo "SENTRY_URL=$SENTRY_URL" | tee -a $GITHUB_ENV
+        echo "DO_PUBLISH=$DO_PUBLISH" | tee -a $GITHUB_ENV
         echo "UPLOAD_ARTIFACT_NAME=$UPLOAD_ARTIFACT_NAME" | tee -a $GITHUB_ENV
 
     - name: Setup environment
@@ -177,13 +187,9 @@ jobs:
                    -DSENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }} \
                    -DSENTRY_PROJECT=${SENTRY_PROJECT} \
                    -P buildscripts/ci/crashdumps/ci_generate_and_upload.cmake
-    - name: Publish package
-      if: inputs.publish == 'on' || (github.event_name == 'schedule' && env.BUILD_MODE == 'nightly')
+    - name: Publish to OSUOSL
+      if: env.DO_PUBLISH == 'true'
       run: |
-        if [ -z "${{ secrets.OSUOSL_SSH_ENCRYPT_SECRET }}" ]; then
-          echo "::warning::OSUOSL_SSH_ENCRYPT_SECRET is not set; not publishing to OSUOSL"
-          exit
-        fi
         sudo bash ./buildscripts/ci/tools/osuosl/publish.sh -s ${{ secrets.OSUOSL_SSH_ENCRYPT_SECRET }} --os linux -v 4
     - name: Upload artifacts on GitHub
       uses: actions/upload-artifact@v4
diff --git a/.github/workflows/build_linux_arm.yml b/.github/workflows/build_linux_arm.yml
--- a/.github/workflows/build_linux_arm.yml
+++ b/.github/workflows/build_linux_arm.yml
@@ -67,7 +67,7 @@ jobs:
     - name: Exit if current release branch configuration is incorrect
       if: ${{ github.event_name == 'schedule' && github.event.schedule == '0 5 */1 */1 *' && env.CURRENT_RELEASE_BRANCH == '' }}
       run: |
-        echo "::error::CURRENT_RELEASE_BRANCH is not set"
+        echo "::error::CURRENT_RELEASE_BRANCH is empty"
         exit 1
     - name: Clone repository (default)
       uses: actions/checkout@v4
@@ -98,7 +98,7 @@ jobs:
         if [[ "$BUILD_MODE" == "testing" || "$BUILD_MODE" == "stable" ]]; then
           DO_UPDATE_TS='true'
           if [ -z "${{ secrets.TRANSIFEX_API_TOKEN }}" ]; then
-            echo "warning: not set TRANSIFEX_API_TOKEN, update .ts disabled"
+            echo "::warning::TRANSIFEX_API_TOKEN is empty; updating .ts files disabled"
             DO_UPDATE_TS='false'
           fi
         fi
@@ -131,6 +131,15 @@ jobs:
           SENTRY_URL=https://sentry.musescore.org/api/3/minidump/?sentry_key=$SENTRY_SERVER_SANDBOX_KEY
         fi
 
+        DO_PUBLISH='false'
+        if ${{ inputs.publish == 'on' }} || (${{github.event_name == 'schedule'}} && [ $BUILD_MODE == 'nightly' ]); then
+          DO_PUBLISH='true'
+          if [ -z "${{ secrets.OSUOSL_SSH_ENCRYPT_SECRET }}" ]; then
+            echo "::warning::OSUOSL_SSH_ENCRYPT_SECRET is empty; not publishing to OSUOSL"
+            DO_PUBLISH='false'
+          fi
+        fi
+
         ADD_INFO="_${GITHUB_REF#refs/heads/}"
         if [ "${{ github.event_name }}" == "schedule" ] && [ "${{ github.event.schedule }}" == "0 5 */1 */1 *" ]; then ADD_INFO="_${CURRENT_RELEASE_BRANCH}"; fi
         if [ "${{ github.event_name }}" == "pull_request" ]; then ADD_INFO="_${{ github.event.pull_request.number }}_${pull_request_title}"; fi
@@ -144,6 +153,7 @@ jobs:
         echo "DO_UPLOAD_SYMBOLS=$DO_UPLOAD_SYMBOLS" | tee -a $GITHUB_ENV
         echo "SENTRY_PROJECT=$SENTRY_PROJECT" | tee -a $GITHUB_ENV
         echo "SENTRY_URL=$SENTRY_URL" | tee -a $GITHUB_ENV
+        echo "DO_PUBLISH=$DO_PUBLISH" | tee -a $GITHUB_ENV
         echo "UPLOAD_ARTIFACT_NAME=$UPLOAD_ARTIFACT_NAME" | tee -a $GITHUB_ENV
 
     - name: Generate _en.ts files
@@ -181,13 +191,9 @@ jobs:
                    -DSENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }} \
                    -DSENTRY_PROJECT=${SENTRY_PROJECT} \
                    -P buildscripts/ci/crashdumps/ci_generate_and_upload.cmake
-    - name: Publish package
-      if: inputs.publish == 'on' || (github.event_name == 'schedule' && env.BUILD_MODE == 'nightly')
+    - name: Publish to OSUOSL
+      if: env.DO_PUBLISH == 'true'
       run: |
-        if [ -z "${{ secrets.OSUOSL_SSH_ENCRYPT_SECRET }}" ]; then
-          echo "::warning::OSUOSL_SSH_ENCRYPT_SECRET is not set; not publishing to OSUOSL"
-          exit
-        fi
         sudo bash ./buildscripts/ci/tools/osuosl/publish.sh -s ${{ secrets.OSUOSL_SSH_ENCRYPT_SECRET }} --os linux --arch armv7l -v 4
     - name: Upload artifacts on GitHub
       uses: actions/upload-artifact@v4
@@ -208,7 +214,7 @@ jobs:
     - name: Exit if current release branch configuration is incorrect
       if: ${{ github.event_name == 'schedule' && github.event.schedule == '0 5 */1 */1 *' && env.CURRENT_RELEASE_BRANCH == '' }}
       run: |
-        echo "::error::CURRENT_RELEASE_BRANCH is not set"
+        echo "::error::CURRENT_RELEASE_BRANCH is empty"
         exit 1
     - name: Clone repository (default)
       uses: actions/checkout@v4
@@ -236,7 +242,7 @@ jobs:
         if [[ "$BUILD_MODE" == "testing" || "$BUILD_MODE" == "stable" ]]; then
           DO_UPDATE_TS='true'
           if [ -z "${{ secrets.TRANSIFEX_API_TOKEN }}" ]; then
-            echo "warning: not set TRANSIFEX_API_TOKEN, update .ts disabled"
+            echo "::warning::TRANSIFEX_API_TOKEN is empty; updating .ts files disabled"
             DO_UPDATE_TS='false'
           fi
         fi
@@ -259,6 +265,15 @@ jobs:
           SENTRY_URL=https://sentry.musescore.org/api/3/minidump/?sentry_key=${{ secrets.SENTRY_SERVER_SANDBOX_KEY }}
         fi
 
+        DO_PUBLISH='false'
+        if [[ "${{ inputs.publish }}" == "on" || ("${{ github.event_name }}" == "schedule" && $BUILD_MODE == 'nightly') ]]; then
+          DO_PUBLISH='true'
+          if [ -z "${{ secrets.OSUOSL_SSH_ENCRYPT_SECRET }}" ]; then
+            echo "::warning::OSUOSL_SSH_ENCRYPT_SECRET is empty; not publishing to OSUOSL"
+            DO_PUBLISH='false'
+          fi
+        fi
+
         ADD_INFO="_${GITHUB_REF#refs/heads/}"
         if [ "${{ github.event_name }}" == "schedule" ] && [ "${{ github.event.schedule }}" == "0 5 */1 */1 *" ]; then ADD_INFO="_${CURRENT_RELEASE_BRANCH}"; fi
         if [ "${{ github.event_name }}" == "pull_request" ]; then ADD_INFO="_${{ github.event.pull_request.number }}_${pull_request_title}"; fi
@@ -272,6 +287,7 @@ jobs:
         echo "DO_UPLOAD_SYMBOLS=$DO_UPLOAD_SYMBOLS" | tee -a "${GITHUB_ENV}"
         echo "SENTRY_PROJECT=$SENTRY_PROJECT" | tee -a "${GITHUB_ENV}"
         echo "SENTRY_URL=$SENTRY_URL" | tee -a "${GITHUB_ENV}"
+        echo "DO_PUBLISH=$DO_PUBLISH" | tee -a "${GITHUB_ENV}"
         echo "UPLOAD_ARTIFACT_NAME=$UPLOAD_ARTIFACT_NAME" | tee -a "${GITHUB_ENV}"
 
     - name: Generate _en.ts files
@@ -310,13 +326,9 @@ jobs:
                    -DSENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }} \
                    -DSENTRY_PROJECT=${SENTRY_PROJECT} \
                    -P buildscripts/ci/crashdumps/ci_generate_and_upload.cmake
-    - name: Publish package
-      if: inputs.publish == 'on' || (github.event_name == 'schedule' && env.BUILD_MODE == 'nightly')
+    - name: Publish to OSUOSL
+      if: env.DO_PUBLISH == 'true'
       run: |
-        if [ -z "${{ secrets.OSUOSL_SSH_ENCRYPT_SECRET }}" ]; then
-          echo "::warning::OSUOSL_SSH_ENCRYPT_SECRET is not set; not publishing to OSUOSL"
-          exit
-        fi
         sudo bash ./buildscripts/ci/tools/osuosl/publish.sh -s ${{ secrets.OSUOSL_SSH_ENCRYPT_SECRET }} --os linux --arch aarch64 -v 4
     - name: Upload artifacts on GitHub
       uses: actions/upload-artifact@v4
diff --git a/.github/workflows/build_windows.yml b/.github/workflows/build_windows.yml
--- a/.github/workflows/build_windows.yml
+++ b/.github/workflows/build_windows.yml
@@ -67,7 +67,7 @@ jobs:
     - name: Exit if current release branch configuration is incorrect
       if: ${{ github.event_name == 'schedule' && github.event.schedule == '0 5 */1 */1 *' && env.CURRENT_RELEASE_BRANCH == '' }}
       run: |
-        echo "::error::CURRENT_RELEASE_BRANCH is not set"
+        echo "::error::CURRENT_RELEASE_BRANCH is empty"
         exit 1
     - name: Clone repository (default)
       uses: actions/checkout@v4
@@ -101,7 +101,7 @@ jobs:
         if [[ "$BUILD_MODE" == "testing" || "$BUILD_MODE" == "stable" ]]; then
           DO_UPDATE_TS='true'
           if [ -z "${{ secrets.TRANSIFEX_API_TOKEN }}" ]; then
-            echo "warning: not set TRANSIFEX_API_TOKEN, update .ts disabled"
+            echo "::warning::TRANSIFEX_API_TOKEN is empty; updating .ts files disabled"
             DO_UPDATE_TS='false'
           fi
         fi
@@ -134,6 +134,15 @@ jobs:
           SENTRY_URL=https://sentry.musescore.org/api/3/minidump/?sentry_key=$SENTRY_SERVER_SANDBOX_KEY
         fi
 
+        DO_PUBLISH='false'
+        if [[ "${{ inputs.publish }}" == "on" || ("${{ github.event_name }}" == "schedule" && $BUILD_MODE == 'nightly') ]]; then
+          DO_PUBLISH='true'
+          if [ -z "${{ secrets.OSUOSL_SSH_ENCRYPT_SECRET }}" ]; then
+            echo "::warning::OSUOSL_SSH_ENCRYPT_SECRET is empty; not publishing to OSUOSL"
+            DO_PUBLISH='false'
+          fi
+        fi
+
         ADD_INFO="_${GITHUB_REF#refs/heads/}"
         if [ "${{ github.event_name }}" == "schedule" ] && [ "${{ github.event.schedule }}" == "0 5 */1 */1 *" ]; then ADD_INFO="_${CURRENT_RELEASE_BRANCH}"; fi
         if [ "${{ github.event_name }}" == "pull_request" ]; then ADD_INFO="_${{ github.event.pull_request.number }}_${pull_request_title}"; fi
@@ -147,6 +156,7 @@ jobs:
         echo "DO_UPLOAD_SYMBOLS=$DO_UPLOAD_SYMBOLS" | tee -a $GITHUB_ENV
         echo "SENTRY_PROJECT=$SENTRY_PROJECT" | tee -a $GITHUB_ENV
         echo "SENTRY_URL=$SENTRY_URL" | tee -a $GITHUB_ENV
+        echo "DO_PUBLISH=$DO_PUBLISH" | tee -a $GITHUB_ENV
         echo "UPLOAD_ARTIFACT_NAME=$UPLOAD_ARTIFACT_NAME" | tee -a $GITHUB_ENV
 
     - name: Setup environment
@@ -196,14 +206,10 @@ jobs:
               -DSENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }} \
               -DSENTRY_PROJECT=${SENTRY_PROJECT} \
               -P buildscripts/ci/crashdumps/ci_generate_and_upload.cmake
-    - name: Publish package
-      if: inputs.publish == 'on' || (github.event_name == 'schedule' && env.BUILD_MODE == 'nightly')
+    - name: Publish to OSUOSL
+      if: env.DO_PUBLISH == 'true'
       shell: bash
       run: |
-        if [ -z "${{ secrets.OSUOSL_SSH_ENCRYPT_SECRET }}" ]; then
-          echo "::warning::OSUOSL_SSH_ENCRYPT_SECRET is not set; not publishing to OSUOSL"
-          exit
-        fi
         bash ./buildscripts/ci/tools/osuosl/publish.sh -s ${{ secrets.OSUOSL_SSH_ENCRYPT_SECRET }} --os windows -v 4
     - name: Upload artifacts on GitHub
       if: ${{ always() }}
@@ -254,7 +260,7 @@ jobs:
         if [[ "$BUILD_MODE" == "testing" || "$BUILD_MODE" == "stable" ]]; then
           DO_UPDATE_TS='true'
           if [ -z "${{ secrets.TRANSIFEX_API_TOKEN }}" ]; then
-            echo "warning: not set TRANSIFEX_API_TOKEN, update .ts disabled"
+            echo "::warning::TRANSIFEX_API_TOKEN is empty; updating .ts files disabled"
             DO_UPDATE_TS='false'
           fi
         fi
@@ -262,6 +268,15 @@ jobs:
         DO_PLACEHOLDER_TRANSLATIONS='false'
         if [[ "$BUILD_MODE" == "nightly" || "$BUILD_MODE" == "devel" ]]; then
           DO_PLACEHOLDER_TRANSLATIONS='true'
+        fi
+
+        DO_PUBLISH='false'
+        if [[ "${{ inputs.publish }}" == "on" || ("${{ github.event_name }}" == "schedule" && $BUILD_MODE == 'nightly') ]]; then
+          DO_PUBLISH='true'
+          if [ -z "${{ secrets.OSUOSL_SSH_ENCRYPT_SECRET }}" ]; then
+            echo "::warning::OSUOSL_SSH_ENCRYPT_SECRET is empty; not publishing to OSUOSL"
+            DO_PUBLISH='false'
+          fi
         fi
 
         ADD_INFO="_${GITHUB_REF#refs/heads/}"
@@ -274,6 +289,7 @@ jobs:
         echo "BUILD_NUMBER=$BUILD_NUMBER" | tee -a $GITHUB_ENV
         echo "DO_UPDATE_TS=$DO_UPDATE_TS" | tee -a $GITHUB_ENV
         echo "DO_PLACEHOLDER_TRANSLATIONS=$DO_PLACEHOLDER_TRANSLATIONS" | tee -a $GITHUB_ENV
+        echo "DO_PUBLISH=$DO_PUBLISH" | tee -a $GITHUB_ENV
         echo "UPLOAD_ARTIFACT_NAME=$UPLOAD_ARTIFACT_NAME" | tee -a $GITHUB_ENV
 
     - name: Setup environment
@@ -311,14 +327,10 @@ jobs:
     - name: Checksum
       run: |
         bash ./buildscripts/ci/tools/checksum.sh
-    - name: Publish package
-      if: inputs.publish == 'on' || (github.event_name == 'schedule' && env.BUILD_MODE == 'nightly')
+    - name: Publish to OSUOSL
+      if: env.DO_PUBLISH == 'true'
       shell: bash
       run: |
-        if [ -z "${{ secrets.OSUOSL_SSH_ENCRYPT_SECRET }}" ]; then
-          echo "::warning::OSUOSL_SSH_ENCRYPT_SECRET is not set; not publishing to OSUOSL"
-          exit
-        fi
         bash ./buildscripts/ci/tools/osuosl/publish.sh -s ${{ secrets.OSUOSL_SSH_ENCRYPT_SECRET }} --os windows -v 4 --arch x86_64-portable
     - name: Upload artifacts on GitHub
       uses: actions/upload-artifact@v4
