upload native debug files to sentry instead of breakpad symbols

diff --git a/.github/workflows/build_linux.yml b/.github/workflows/build_linux.yml
--- a/.github/workflows/build_linux.yml
+++ b/.github/workflows/build_linux.yml
@@ -177,7 +177,8 @@ jobs:
         fi
 
         if [ -z "$SENTRY_PROJECT" ] && [ "$BUILD_MODE" == "nightly" ]; then
-          SENTRY_PROJECT="mu4-sandbox"
+          # DO_UPLOAD_SYMBOLS is turned off because the files are large, and sending them every night is costly
+          SENTRY_URL=https://sentry.musescore.com/api/3/minidump/?sentry_key=$SENTRY_MUSE_MU4_SANDBOX_KEY
         fi
 
         if [ "$SENTRY_PROJECT" == "mu4-sandbox" ] && [ "$SENTRY_MUSE_MU4_SANDBOX_KEY" != "" ]; then
@@ -268,21 +269,19 @@ jobs:
     - name: Checksum
       run: |
         bash ./buildscripts/ci/tools/checksum.sh
-    - name: Generate and upload dump symbols
+
+    - name: Upload debug files
       if: env.DO_UPLOAD_SYMBOLS == 'true'
       env:
+        SENTRY_URL: https://sentry.musescore.com
         SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_MUSE_AUTH_TOKEN }}
+        SENTRY_ORG: sentry
       run: |
-        APP_BIN=$(find "$(pwd)/build.release/src/app/" -type f -name "mscore4portable*" -print -quit)
-        ARCH=${{ matrix.dump-symbols-arch }}
-        sudo cmake -DAPP_BIN=${APP_BIN} \
-                   -DARCH=${ARCH} \
-                   -DSENTRY_URL=https://sentry.musescore.com \
-                   -DSENTRY_ORG=sentry \
-                   -DSENTRY_AUTH_TOKEN="${SENTRY_AUTH_TOKEN}" \
-                   -DSENTRY_PROJECT=${SENTRY_PROJECT} \
-                   -DSTAGE=${BUILD_MODE} \
-                   -P buildscripts/ci/crashdumps/ci_generate_and_upload.cmake
+        APP_BIN=$(find build.release/src/app/ -type f -name 'mscore4portable*' -print -quit)
+        if [ -z "$APP_BIN" ]; then echo "error: app binary not found"; exit 1; fi
+
+        cmake -DFILES="$APP_BIN" -P ./muse/buildscripts/ci/tools/sentry/upload_debug_files.cmake
+
     - name: Publish to OSUOSL
       if: env.DO_PUBLISH == 'true'
       env:
